### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Dreamlikec** [Doubiiu/ToonCrafter#54]
I saw that you collected 270K cartoon video clips in this paper, will you open this dataset in the future?

**Comment by BPAWD** [comment]
Same question. At least the 1K evaluation set should be provided for fair comparisons with future works.

**Comment by Doubiiu** [comment]
Hi Thanks for your interest. We cannot release the dataset due to copyright issues (as we're not allowed for re-distribution).
